.TH "pileCard" 3 "Version 1" "Re'Belotte" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pileCard \- Structure representing a pile of cards (deck or team's won cards)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <moteur\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "enum \fBcard\fP \fBdeck\fP [\fBNB_CARD_DECK\fP]"
.br
.RI "Array of cards in the pile\&. "
.ti -1c
.RI "int \fBlastcard\fP"
.br
.RI "Index of the last card dealt/added\&. "
.in -1c
.SH "Detailed Description"
.PP 
Structure representing a pile of cards (deck or team's won cards) 

.SH "Author"
.PP 
Generated automatically by Doxygen for Re'Belotte from the source code\&.
