.TH "include/servApp.h" 3 "Version 1" "Re'Belotte" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/servApp.h \- Header file for the application server of the Belote card game\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <pthread\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'libRepReq\&.h'\fP
.br
\fC#include 'moteur\&.h'\fP
.br
\fC#include 'client\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBafficherMenu\fP ()"
.br
.RI "Displays the main menu with available game options\&. "
.ti -1c
.RI "int \fBchoisir\fP ()"
.br
.RI "Prompts the user to enter their menu choice\&. "
.ti -1c
.RI "int \fBconnexionToSE\fP (\fBsocket_t\fP *sdSE, char *nomUtilisateur)"
.br
.RI "Establishes a connection to the registration server (SE) "
.ti -1c
.RI "int \fBcreerPartieSe\fP (\fBsocket_t\fP *sdSE, char *nomUtilisateur)"
.br
.RI "Creates a new game session on the registration server\&. "
.ti -1c
.RI "int \fBdemanderAffichagePartiesUtilisateur\fP (\fBsocket_t\fP *sdSE)"
.br
.RI "Requests and displays the list of available games with users\&. "
.ti -1c
.RI "int \fBchoisirPartieUtilisateur\fP (\fBsocket_t\fP *sdSE, char *IPUtilisateur, int *portUtilisateur)"
.br
.RI "Allows the user to select and join a specific user's game\&. "
.ti -1c
.RI "void \fBgestionPartie\fP (\fBsocket_t\fP *sdSE, char *nomUtilisateur)"
.br
.RI "Manages a game as the host server\&. "
.ti -1c
.RI "void \fBrejoindrePartie\fP (\fBsocket_t\fP *sdSE)"
.br
.RI "Joins an existing game hosted by another user\&. "
.ti -1c
.RI "int \fBrejoindrePartieAleatoire\fP (\fBsocket_t\fP *sdSE, char *nomUtilisateur)"
.br
.RI "Joins a random available game or creates a new one if none exists\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header file for the application server of the Belote card game\&. 

This header defines the data structures, enumerations, and function prototypes for implementing the French card game Belote for 4 players in 2 teams\&. 
.PP
\fBAuthor\fP
.RS 4
Vaniet Quentin 
.RE
.PP
\fBDate\fP
.RS 4
04/02/2026 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void afficherMenu ()"

.PP
Displays the main menu with available game options\&. Shows options to create a game, join a user's game, join a random game, or quit 
.SS "int choisir ()"

.PP
Prompts the user to enter their menu choice\&. 
.PP
\fBReturns\fP
.RS 4
The integer value corresponding to the user's choice 
.RE
.PP

.SS "int choisirPartieUtilisateur (\fBsocket_t\fP * sdSE, char * IPUtilisateur, int * portUtilisateur)"

.PP
Allows the user to select and join a specific user's game\&. 
.PP
\fBParameters\fP
.RS 4
\fIsdSE\fP Pointer to the socket descriptor for the registration server 
.br
\fIIPUtilisateur\fP Buffer to store the IP address of the selected game host 
.br
\fIportUtilisateur\fP Pointer to store the port number of the selected game host 
.RE
.PP
\fBReturns\fP
.RS 4
0 on success, -1 on failure (game full or error) 
.RE
.PP

.SS "int connexionToSE (\fBsocket_t\fP * sdSE, char * nomUtilisateur)"

.PP
Establishes a connection to the registration server (SE) 
.PP
\fBParameters\fP
.RS 4
\fIsdSE\fP Pointer to the socket descriptor for the registration server 
.br
\fInomUtilisateur\fP Buffer to store the username entered by the user 
.RE
.PP
\fBReturns\fP
.RS 4
0 on success, -1 on failure 
.RE
.PP

.SS "int creerPartieSe (\fBsocket_t\fP * sdSE, char * nomUtilisateur)"

.PP
Creates a new game session on the registration server\&. 
.PP
\fBParameters\fP
.RS 4
\fIsdSE\fP Pointer to the socket descriptor for the registration server 
.br
\fInomUtilisateur\fP The username of the player creating the game 
.RE
.PP
\fBReturns\fP
.RS 4
0 on success, -1 on failure 
.RE
.PP

.SS "int demanderAffichagePartiesUtilisateur (\fBsocket_t\fP * sdSE)"

.PP
Requests and displays the list of available games with users\&. 
.PP
\fBParameters\fP
.RS 4
\fIsdSE\fP Pointer to the socket descriptor for the registration server 
.RE
.PP
\fBReturns\fP
.RS 4
0 on success, -1 on failure 
.RE
.PP

.SS "void gestionPartie (\fBsocket_t\fP * sdSE, char * nomUtilisateur)"

.PP
Manages a game as the host server\&. Creates a listening socket, waits for 3 players to connect, initializes the game engine, and handles game execution and cleanup 
.PP
\fBParameters\fP
.RS 4
\fIsdSE\fP Pointer to the socket descriptor for the registration server 
.br
\fInomUtilisateur\fP The username of the player hosting the game 
.RE
.PP

.SS "void rejoindrePartie (\fBsocket_t\fP * sdSE)"

.PP
Joins an existing game hosted by another user\&. Displays available games and prompts the user to select one to join 
.PP
\fBParameters\fP
.RS 4
\fIsdSE\fP Pointer to the socket descriptor for the registration server 
.RE
.PP

.SS "int rejoindrePartieAleatoire (\fBsocket_t\fP * sdSE, char * nomUtilisateur)"

.PP
Joins a random available game or creates a new one if none exists\&. 
.PP
\fBParameters\fP
.RS 4
\fIsdSE\fP Pointer to the socket descriptor for the registration server 
.br
\fInomUtilisateur\fP The username of the player 
.RE
.PP
\fBReturns\fP
.RS 4
0 on success, -1 on failure 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Re'Belotte from the source code\&.
