.TH "socket" 3 "Version 1" "Re'Belotte" \" -*- nroff -*-
.ad l
.nh
.SH NAME
socket \- Socket data structure definition\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <session\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBfd\fP"
.br
.RI "File descriptor of the created socket\&. "
.ti -1c
.RI "int \fBmode\fP"
.br
.RI "Connection mode: SOCK_STREAM (TCP) or SOCK_DGRAM (UDP) "
.ti -1c
.RI "struct sockaddr_in \fBaddrLoc\fP"
.br
.RI "Local address of the socket\&. "
.ti -1c
.RI "struct sockaddr_in \fBaddrDst\fP"
.br
.RI "Remote/destination address of the socket\&. "
.in -1c
.SH "Detailed Description"
.PP 
Socket data structure definition\&. 

This structure encapsulates all information related to a socket, including its file descriptor, connection mode, and both local and remote address information\&. It provides a complete representation of a socket for both client and server applications\&.
.PP
\fBNote\fP
.RS 4
This type is composed of the socket file descriptor, mode (connected/non-connected), and application addresses (local/remote) 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Re'Belotte from the source code\&.
