.TH "user_t" 3 "Version 1" "Re'Belotte" \" -*- nroff -*-
.ad l
.nh
.SH NAME
user_t \- Représente un utilisateur du système\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <users\&.h>\fP
.SH "Detailed Description"
.PP 
Représente un utilisateur du système\&. 

Un utilisateur est identifié par un nom, une socket de dialogue, un éventuel destinataire pour la communication, et une partie associée\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Re'Belotte from the source code\&.
